### ISSUE TITLE
Make Test case not failed when offline

### ISSUE THREAD

**Issue by suryadina** [A9T9/RPA#30]
[error] ipcPromise: onAsk timeout 60000 for cmd "PANEL_RUN_COMMAND", args "[object Object]"
[info] Test case failed (Runtime 121.18s)

Hi. can you make kantu not stopped when the computer's connection is offline? I would like to automate a simple task which push a button in a webpage every hour all day long. The problem is, sometimes connection at my place lost. If kantu can ignore offline page or wait until the connection is back, it will really helps me because I don't need to check if the macros is still running.

Thanks

**Comment by A9T9** [comment]
[Todays update (V2.5) ](https://a9t9.com/kantu/web-automation/chrome/whatsnew) should fix this. If not, please reopen the ticket.

**Comment by suryadina** [comment]
Hi. I'm sorry, but the problem is not fixed. I have tried the new version, I played a macros with loop and in the middle of the test I cut off the connection. After 60000ms the macros show this error again

[error] ipcPromise: onAsk timeout 60000 for cmd "PANEL_RUN_COMMAND", args "[object Object]"

One more issue. I also tested a macros with the above scenario, but before it went timeout, I bring back the connection. Unfortunately, it looks like Kantu couldn't recognized that the connection already back.

My request is, please make Kantu can recognized when the page failed to load (maybe because of the connection problem) and then make it be able to try loading the page again (refresh the page) with a controllable try interval. Thanks
